global:
  environment: dev-idan
  project: development
data-node:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::337450623971:role/hyperspace-dev-idan-EC2TagsPolicy
  replicaCount: 0
  image:
    tag: latest
    pullPolicy: IfNotPresent
  config:
    log_level: DEBUG
    restore_from_rocksdb: true
  ebsVolume:
    enabled: true
  priorityClass:
    enabled: false
  hugePages:
    enabled: true
    numOfHugePages: 100
  readinessProbe:
    failureThreshold: 720
    periodSeconds: 10
  startupProbe:
    failureThreshold: 720
    periodSeconds: 10
compiler-service:
  image:
    tag: latest
    pullPolicy: Always
realtime-compiler:
  image:
    tag: latest
    pullPolicy: Always
search-master:
  ingress:
    className: "nginx-internal"
    hosts:
      - host: test.internal-dev-idan.hyper-space.xyz
        paths:
          - path: /
            pathType: Prefix
          - path: /api/v1/([^/]+)/document/add
            pathType: Prefix
          - path: /api/v1/([^/]+)/batch
            pathType: Prefix
  image:
    tag: latest
    pullPolicy: Always
  config:
    log_level: DEBUG
    restore: false
    commit_timeout: 120000
etcd-backup:
  schedule_cron: 0 13 * * *
  role_arn: arn:aws:iam::471112693898:role/hyperspace-etcd-backup-development-role
  etcdBackup:
    enabled: false
redis:
  master:
    count: 0
