apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.environment }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.environment }}
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
  # Admin role for dev team
    - name: admin
      description: admin role on the project
      policies:
        - p, proj:{{ .Values.environment }}:admin, applications, get, {{ .Values.environment }}/*, allow
        - p, proj:{{ .Values.environment }}:admin, applications, sync, {{ .Values.environment }}/*, allow
        - p, proj:{{ .Values.environment }}:admin, repositories, create, {{ .Values.environment }}/*, allow
        - p, proj:{{ .Values.environment }}:admin, repositories, delete, {{ .Values.environment }}/*, allow
        - p, proj:{{ .Values.environment }}:admin, repositories, update, {{ .Values.environment }}/*, allow
      groups:
        - hyper-space-io:Argo-Production-Access